import js from "@eslint/js";
import prettier from "eslint-config-prettier";

export default [
  js.configs.recommended,
  prettier,
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        console: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        AbortController: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        Blob: "readonly",
        FormData: "readonly",
        Response: "readonly",
        XMLHttpRequest: "readonly",
        DOMParser: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        Element: "readonly",
        HTMLElement: "readonly",
        Node: "readonly",
        crypto: "readonly",
        module: "readonly",
        require: "readonly",
        Auth: "readonly",
        MOVIES_DATABASE: "readonly",
        Security: "readonly",
        escapeHtml: "readonly",
        escapeText: "readonly",
        ThemeToggle: "readonly",
        I18n: "readonly",
        showToast: "writable",
        showToastError: "writable",
        openUploadModal: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^(e|_)\\b" }],
      "no-undef": "error",
      "no-redeclare": "off",
      "no-duplicate-case": "error",
      "no-unreachable": "warn",
      "eqeqeq": ["warn", "always"],
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-script-url": "error",
      "no-alert": "warn",
      "no-var": "warn",
      "prefer-const": "warn",
      "no-useless-escape": "warn",
      "no-self-compare": "warn",
      "no-empty": ["error", { allowEmptyCatch: true }],
    },
  },
  {
    ignores: ["node_modules/", "lib/", "*.min.js"],
  },
];
